Protfolio mobile version
mrkamin/Portfolio-mobile-version-final pull request #1
Opened 2022-09-30 13:50 UTC by mrkamin

Portfolio Mobile Version final PR

2022-09-30 13:52 UTC, mrkamin commented
PortFolio mobile version PR

2022-09-30 14:07 UTC, cwaku reviewed
Hi @mrkamin 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

It seems like you have submitted the wrong PR URL. It shows to me in the dashboard that this is a re-review but otherwise here and there is no note that a previous reviewer requested that you make a new PR. Kindly resubmit.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-30 16:08 UTC, jaflih requested changes
Hi @mrkamin  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
✔️ Linters passed 💯
✔️ The content is aligned with flexbox 🥇 
✔️ Great commit history

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @jaflih in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 16:08 UTC, jaflih commented on style.css
> +  width: 600px;
Please correct your responsive in mobile view.
I can scroll right/left but it is not in the requirement.
<img width="439" alt="Capture d’écran 2022-09-30 à 18 04 02" src="https://user-images.githubusercontent.com/7243132/193311423-3f929e46-e020-4898-91fd-3bdf0b63a79f.png">

2022-09-30 16:08 UTC, jaflih commented on style.css
> +}
Please refer to the template guide to have a design close to Figma.


When the user hovers or presses the button, we. want this effect 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/7243132/193310620-85100412-e9a2-482a-8898-900480abd58c.png">

2022-09-30 23:51 UTC, mrkamin commented
correction RWD

2022-10-01 17:10 UTC, rukundoeric requested changes
Hello @mrkamin  👋,

_This is an additional review as a result of the second opinion request._

As mentioned by the previous reviewer, please follow the figma design for buttons events:

![Screen Shot 2022-10-01 at 19 04 24](https://user-images.githubusercontent.com/7243132/193310620-85100412-e9a2-482a-8898-900480abd58c.png)

Currently what you have is 
![Screen Shot 2022-10-01 at 19 04 24](https://user-images.githubusercontent.com/45217364/193420490-e0d01657-3255-4c00-9cfc-e9ec62042823.png)


Keep rocking 🚀! // can be customized

@rukundoeric 
thanks for your good and valuable feedback.
I will try my best to fix the issue.

2022-10-03 07:23 UTC, Nemwel-Boniface approved these changes
## Hello @mrkamin          :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] [OPTIONAL] To fix the horizontal scroll, you can consider adding the below lines of code in your style.css file.

```
html,
body {
  overflow-x: hidden;
}
```

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@Nemwel-Boniface 
thanks for your good and valuable feedback and suggestions. 
I will consider your suggestions in my upcoming projects.

2023-03-23 15:32 UTC, mrkamin commented on style.css
> +  width: 600px;
@jaflih 
thanks for your good and valuable feedback.

2023-03-23 15:33 UTC, mrkamin commented on style.css
> +}
@jaflih 
thanks for your good and valuable feedback. 
I will consider your feedback in my next attempt.

2023-03-23 15:37 UTC, merged